# Generated by Django 5.2 on 2026-05-19 17:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "target_muscle_group",
                    models.CharField(
                        help_text="e.g., Chest, Back, Quads", max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight in kg", max_digits=5
                    ),
                ),
                (
                    "fitness_goal",
                    models.CharField(
                        choices=[
                            ("BULK", "Caloric Surplus / Hypertrophy"),
                            ("CUT", "Caloric Deficit / Fat Loss"),
                            ("MAINTAIN", "Maintenance"),
                        ],
                        default="BULK",
                        max_length=10,
                    ),
                ),
                ("target_protein", models.PositiveIntegerField(help_text="grams")),
                ("target_carbs", models.PositiveIntegerField(help_text="grams")),
                ("target_fats", models.PositiveIntegerField(help_text="grams")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "split_name",
                    models.CharField(
                        choices=[
                            ("PUSH", "Push"),
                            ("PULL", "Pull"),
                            ("LEGS", "Legs"),
                            ("ARNOLD_CHEST_BACK", "Arnold Split - Chest & Back"),
                            ("ARNOLD_ARM_SHOULDER", "Arnold Split - Arms & Shoulders"),
                            ("ARNOLD_LEGS", "Arnold Split - Legs"),
                        ],
                        max_length=25,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                (
                    "session_rpe",
                    models.PositiveSmallIntegerField(
                        help_text="Rate of Perceived Exertion (1-10) for the whole session",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveSmallIntegerField()),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight lifted in kg", max_digits=6
                    ),
                ),
                ("reps", models.PositiveSmallIntegerField()),
                (
                    "rpe",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="RPE (1-10) for this specific set",
                        null=True,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="analytics.exercise",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="analytics.workoutlog",
                    ),
                ),
            ],
            options={
                "ordering": ["workout", "exercise", "set_number"],
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("protein_consumed", models.PositiveIntegerField(default=0)),
                ("carbs_consumed", models.PositiveIntegerField(default=0)),
                ("fats_consumed", models.PositiveIntegerField(default=0)),
                ("calories_consumed", models.PositiveIntegerField(default=0)),
                (
                    "sleep_hours",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "soreness_level",
                    models.PositiveSmallIntegerField(
                        help_text="Scale 1-5: 1 being fresh, 5 being severely fatigued",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
